shallow_clone: true

os:
  - Visual Studio 2019

environment:
  matrix:
  - TOOLSET: vs2019

clone_script:
- cmd: >-
    git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%

install:
  - set PATH=C:\Ruby23-x64\bin;%PATH%
  - bundle install

build_script:
  - make.bat %CONFIGURATION% %PLATFORM%

after_build:
  - ruby bin/blitz3d help --build
  - cd %APPVEYOR_BUILD_FOLDER%\_release && 7z a ..\release.zip bin\*.exe bin\*.dll cfg Games help Media mediaview samples tutorials userlibs *.exe versions.txt

configuration:
  - debug
  - release

platform:
  - win32
  - win64

artifacts:
  - path: release.zip
    name: Full Release

  - path: _release\bin\runtime.*.dll
    name: Runtimes

  - path: _release\bin\linker.dll
    name: Linker

  - path: _release\bin\blitzcc.exe
    name: Compiler

  - path: _release\bin\ide.exe
    name: IDE

  - path: _release\help
    name: Help
